<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Entities\BBBoardInfo;

use \Config;
/*
php artisan make:controller BBBoardFetch --resource (infact doesnt need resource(to create CRUD ops))
Controller created successfully.
php artisan make:model Entities\BBBoardInfo
Model created successfully.
*/

class BBBoardFetch extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // 
        //when it be accessed without any parameter
        $sessionID = Config::get('hackathon.game_session.id');
        $gameLogicURL = Config::get('hackathon.game_logic.presenter.round.url');
        $sFullURL = $gameLogicURL . "/" . $sessionID . "/token";
        
        $result = file_get_contents($sFullURL);

        return response()->json(json_decode($result), 200);
    }

    public function indexWithSessionId($sessionID, $stepIdx) {
        //
        //the new method, it will be accessed with a sessionid, 
        //which is dynamically generated by board init API
        $gameLogicURL = Config::get('hackathon.game_logic.presenter.round.url');
        $sFullURL = $gameLogicURL . "/" . $sessionID . "/" . $stepIdx;
        
        $result = file_get_contents($sFullURL);

        return response()->json(json_decode($result), 200);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}
